### ISSUE TITLE
李宏毅深度学习教程LeeDL-Tutorial

### ISSUE THREAD

**Issue by qiwang067** [datawhalechina/DOPMC#108]
### 你是否已经阅读并同意《Datawhale开源项目指南》？

- [X] 我已阅读并同意[《Datawhale开源项目指南》](https://github.com/datawhalechina/DOPMC/blob/main/GUIDE.md)

### 你是否已经阅读并同意《Datawhale开源项目行为准则》？

- [X] 我已阅读并同意[《Datawhale开源项目行为准则》](https://github.com/datawhalechina/DOPMC/blob/main/CODE_OF_CONDUCT.md)

### 项目简介

李宏毅老师是台湾大学的教授，其[《机器学习（2021年春）》](https://speech.ee.ntu.edu.tw/~hylee/ml/2021-spring.html)是深度学习领域经典的中文视频之一。李老师幽默风趣的授课风格深受大家喜爱，让晦涩难懂的深度学习理论变得轻松易懂，他会通过很多动漫相关的有趣例子来讲解深度学习理论。李老师的课程内容很全面，覆盖了到深度学习必须掌握的常见理论，能让学生对于深度学习的绝大多数领域都有一定了解，从而可以进一步选择想要深入的方向进行学习，对于想入门深度学习又想看中文讲解的同学是非常推荐的

本教程主要内容源于[《机器学习（2021年春）》](https://speech.ee.ntu.edu.tw/~hylee/ml/2021-spring.html)，并在其基础上进行了一定的原创。比如，为了尽可能地降低阅读门槛，笔者对这门公开课的精华内容进行选取并优化，对所涉及的公式都给出详细的推导过程，对较难理解的知识点进行了重点讲解和强化，以方便读者较为轻松地入门。此外，为了丰富内容，笔者在教程中选取了[《机器学习（2017年春）》](https://speech.ee.ntu.edu.tw/~hylee/ml/2017-spring.php) 的部分内容，并补充了不少除这门公开课之外的深度学习相关知识。

李宏毅深度学习教程 GitHub 链接：https://github.com/qiwang067/leedl-tutorial

### 立项理由

让深度学习的爱好者，更好地入门深度学习。

### 项目受众

对深度学习感兴趣，想要入门深度学习的读者。

### 项目亮点

已有类似项目：[李宏毅机器学习笔记](https://github.com/datawhalechina/leeml-notes)

不同之处：
- 本教程主要涉及深度学习的内容，采用[《机器学习（2021年春）》](https://speech.ee.ntu.edu.tw/~hylee/ml/2021-spring.html) 作为基础进行优化，其内容与[《机器学习（2017年春）》](https://speech.ee.ntu.edu.tw/~hylee/ml/2017-spring.php)  有很大的不同，以最新的深度学习知识为主。
- 本教程不仅是对李宏毅课程的整理，会在其基础上进行了一定的原创、优化。
- 本教程使用 LaTeX 进行排版，读者有更好的阅读体验。

### 项目规划

* **引言** @王琦
* **深度学习** @王琦
    *  [x] 局部最小值与鞍点
    *  [ ] 训练技巧
    *  [ ] 自适应学习率
    *  [ ] 分类问题损失函数
    *  [ ] 归一化
* **卷积神经网络和自注意力机制** @王琦
  *  [x] 卷积神经网络
  *  [x] 自注意力机制
* **循环神经网络** @王琦
* **Transformer** @王琦
  *  [x] Transformer
* **生成模型** @杨毅远
*  [x] 生成对抗网络基础
*  [ ] 生成对抗网络理论与 Wasserstein 生成对抗网络
*  [ ] 生成对抗网络的评估与有条件的生成对抗网络
*  [ ] 循环生成对抗网络
* **自监督学习** @王琦
  *  [x] 芝麻街的模型
  *  [x] BERT
  *  [x] GPT-3
* **自动编码器概念及其应用** @江季
* **对抗攻击** @杨毅远
*  [ ] 对抗攻击基本概念
*  [ ] 对抗攻击的攻击与防守
* **可解释人工智能** @杨毅远
* **迁移学习** @王琦
  *  [ ] 领域自适应
  *  [ ] 领域对抗训练
* **深度强化学习** @王琦
  *  [ ] 深度强化学习基础
  *  [ ] 策略梯度
  *  [ ] 演员-评论员算法
  *  [ ] 稀疏奖励
  *  [ ] 模仿学习
* **终身学习** @杨毅远
  *  [ ] 灾难性遗忘
  *  [ ] 缓解灾难性遗忘 
* **网络压缩** @王琦
  *  [ ] 剪枝与彩票假设
  *  [ ] 知识蒸馏
* **集成学习** @王琦
* **元学习** @杨毅远 

预计完成日期：2023年6月1日

### 项目负责人

- 王琦，[GitHub 主页](https://github.com/qiwang067)，联系方式：qiwang067@163.com
- 杨毅远，[GitHub 主页](https://github.com/yyysjz1997)，联系方式：yyy1997sjz@gmail.com
- 江季，[GitHub 主页](https://github.com/johnjim0816)，联系方式：2443844439@qq.com

### 备注：发起立项申请后DOPMC将会在 72h 之内给出答复，如超时未答复请添加DOPMC负责人微信（微信号：at-Sm1les）问询~

- [X] 我已知悉上述备注

**Comment by GYHHAHA** [comment]
和[这个](https://github.com/datawhalechina/DOPMC/issues/55)是什么关系？

**Comment by qiwang067** [comment]
> 和[这个](https://github.com/datawhalechina/DOPMC/issues/55)是什么关系？

基本没有关系，[这个](https://github.com/datawhalechina/DOPMC/issues/55) 主要是机器学习的内容，而本教程是深度学习的内容，这一点可以从目录中看出。
唯一有一点关系的是，本教程会选择跟[这个](https://github.com/datawhalechina/DOPMC/issues/55) 所基于的  [《机器学习（2017年春）》](https://speech.ee.ntu.edu.tw/~hylee/ml/2017-spring.php) 部分内容进行补充，让教程更加全面。

具体的不同之处已在项目亮点之处说明：
<img width="822" alt="image" src="https://user-images.githubusercontent.com/22296010/211701476-7052724e-45d6-4fc6-a373-e8d7ab95d9ca.png">

**Comment by GYHHAHA** [comment]
应该是那个issue的title写错了 @Sm1les ，cc

**Comment by GYHHAHA** [comment]
同意

**Comment by zhanhao93** [comment]
同意

**Comment by zhanhao93** [comment]
李宏毅2022的课程就是直接从DL开始的了
https://speech.ee.ntu.edu.tw/~hylee/ml/2022-spring.php
可以参考这个

**Comment by qiwang067** [comment]
感谢各位兄弟的反馈和建议，经过讨论，我们决定在原有的 [leeml-notes](https://github.com/datawhalechina/leeml-notes) 这个仓库的基础上进行维护升级，终止当前这个立项。
