### ISSUE TITLE
面经项目第二版

### ISSUE THREAD

**Issue by Richman-wang** [datawhalechina/DOPMC#123]
### 你是否已经阅读并同意《Datawhale开源项目指南》？

- [X] 我已阅读并同意[《Datawhale开源项目指南》](https://github.com/datawhalechina/DOPMC/blob/main/GUIDE.md)

### 你是否已经阅读并同意《Datawhale开源项目行为准则》？

- [X] 我已阅读并同意[《Datawhale开源项目行为准则》](https://github.com/datawhalechina/DOPMC/blob/main/CODE_OF_CONDUCT.md)

### 项目简介

项目地址：https://github.com/datawhalechina/daily-interview

**面经项目第二版**是在第一版的基础上进行迭代更新，希望在该项目中完善NLP、CV、开发、以及数据科学等领域常见面试内容，以帮助到更多求职群体。此外，还希望在该项目中，加入一些场景题目（比如在最后主管面的时候，一般都会问场景题目，希望能有大佬对这部分比较熟悉的，能够对这部分的题目进行拆解和分析）。

### 立项理由

随着各厂缩减招聘名额，对求职者的要求自然也就水涨船高。我们希望通过这份面经，能够帮助到更多有需要的人，在春招或者秋招道路上，斩获自己心仪的offer。由于知识在不断的更新，面经项目也需要在之前的基础上进行迭代。

### 项目受众

针对所有求职有需要的人群，当然我们更希望我们整理的这份面经，能够让更多的学生群体，得到受益。在最后求职过程中，帮他们度过最后“一公里路程”。

### 项目亮点

市面上有很多面经，但答案有的各执一言，有的零零散散，有的写的高深难懂。希望由Datawhale成员整理的面经，既能够囊括常见的高频面试题，也能够把面试题目讲解透彻，更能够通俗易懂。让基础不那么扎实的同学能够通过这份面经差缺补漏，提高面试的成功率。

**本项目亮点如下：**

1. 覆盖面广，包含机器学习基础、NLP、CV、开发、数据分析等。
2. 面向普通大众，由浅入深讲解，语言追求通俗易懂。
3. 尝试与其他实战课程进行联结，将实战课程作为项目，从项目中挖掘面试时常见问题。

### 项目规划

**目录**（暂定）

1. 机器学习基础篇（目前该部分已完成）
2. 深度学习篇
- CV
- NLP
- 推荐
3. 数据科学&数据分析
4. 开发
- 前端
- 后端
5. 计算机基础
- 高数以及概率统计相关知识
- 操作系统
- 数据库等

**预计完成日期**
2023年7月，在秋招开始之前

** 可预见困难**
- 工程量大，需要更多的开源贡献者参与
- 后期校对，需要过硬的专业知识

### 项目负责人

**汪健麟**，电子科技大学硕士，西安电子科技大学杭州研究院算法工程师
**邮箱**：wangjianlin_uestc@163.com
***Github**：[https://github.com/Richman-wang](@Richman-wang )

### 备注：发起立项申请后DOPMC将会在 72h 之内给出答复，如超时未答复请添加DOPMC负责人微信（微信号：at-Sm1les）问询~

- [X] 我已知悉上述备注

**Comment by finlay-liu** [comment]
同意

**Comment by GYHHAHA** [comment]
同意

**Comment by qiwang067** [comment]
同意

**Comment by NoFish-528** [comment]
同意

**Comment by zhanhao93** [comment]
同意，还可以邀请一些datawhale的成员来分享

**Comment by andongBlue** [comment]
同意，还能做一些面试的串讲，不是按知识点，而是按面试流程

**Comment by mba1398** [comment]
同意

**Comment by ruyiluo** [comment]
同意

**Comment by skywateryang** [comment]
同意

**Comment by Sm1les** [comment]
同意

**Comment by ruyiluo** [comment]
同意
