### ISSUE TITLE
fun-rl

### ISSUE THREAD

**Issue by Evan-wyl** [datawhalechina/DOPMC#129]
### 你是否已经阅读并同意《Datawhale开源项目指南》？

- [X] 我已阅读并同意[《Datawhale开源项目指南》](https://github.com/datawhalechina/DOPMC/blob/main/GUIDE.md)

### 你是否已经阅读并同意《Datawhale开源项目行为准则》？

- [X] 我已阅读并同意[《Datawhale开源项目行为准则》](https://github.com/datawhalechina/DOPMC/blob/main/CODE_OF_CONDUCT.md)

### 项目简介

根据综述文章，系统梳理单智能体强化学习的相关知识。

### 立项理由

本来是正在系统梳理MARL，在梳理过程中也产生了系统梳理单智能体强化学习知识的想法。
出一本属于自己的书～

### 项目受众

1. 对强化学习感兴趣的同学。
2. 想系统学习强化学习理论知识的同学。

### 项目亮点

1. 重在系统性，几乎涵盖强化学习的各个领域，例如：offline RL。
2. 对强化学习的基础理论也进行了介绍。
3. 适合于现代学习需求的知识总结。

### 项目规划

至少包括以下内容：
1.目录（如有多级至少精确到二级）
2.各章节负责人
3.各章节预估完成日期
4.可预见的困难

#### 目录
参见：https://github.com/Evan-wyl/fun-rl

### 项目负责人

Github: https://github.com/Evan-wyl
微信: Evan_wyl

### 备注：发起立项申请后DOPMC将会在 72h 之内给出答复，如超时未答复请添加DOPMC负责人微信（微信号：at-Sm1les）问询~

- [X] 我已知悉上述备注

**Comment by mba1398** [comment]
请问 fun-rl、fun-marl 和 easy-rl、JoyRL 是什么关系？是强化学习的不同领域吗？

**Comment by Evan-wyl** [comment]
> 请问 fun-rl、fun-marl 和 easy-rl、JoyRL 是什么关系？是强化学习的不同领域吗？

fun-rl注重强化学习的系统性，几乎涵盖强化学习的各个领域；fun-marl是系统性总结marl。
个人理解，fun-rl会比easy-rl覆盖面更广；JoyRL重在实践。

**Comment by NoFish-528** [comment]
能否在原有课程基础上进行整合？期待一下样章~

**Comment by ruyiluo** [comment]
社区强化学习相关的基础内容已经有了，fun-rl 和 fun-marl 可以着重一个做出来

**Comment by Evan-wyl** [comment]
> 社区强化学习相关的基础内容已经有了，fun-rl 和 fun-marl 可以着重一个做出来

明白你的意思了，ok!

**Comment by zhanhao93** [comment]
建议突出和之前项目的区别度，或者在其基础上进行整合
