### ISSUE TITLE
Datawhale 社区成员数据库项目

### ISSUE THREAD

**Issue by siyuxin** [datawhalechina/DOPMC#27]
### 项目背景
伴随组织发展，仅依靠原有的微信群、飞书等方式难以支持组织成员间相互连接，并支持项目发展，为提高组织人员连接效率，故需要设计组织成员数据库
### 项目计划
1. 调研需求
2. 数据库建模，明确数据库字段
3. MVP产品和技术选型
4. 收集成员数据 & 数据库开发
5. 数据库维护

### 项目组成员：
   袁明坤 @Gookr5 、司玉鑫 、姜诗扬，有意向参与数据库项目，欢迎联系

**Comment by Gookr5** [comment]
您所发送的邮件已收到，谢谢！

**Comment by Gookr5** [comment]
您所发送的邮件已收到，谢谢！
