### ISSUE TITLE
Polars教程

### ISSUE THREAD

**Issue by Sm1les** [datawhalechina/DOPMC#29]
### 项目简介
Polars中文教程
### 项目负责人
@linjing-lab
### 项目地址
[]()

**Comment by linjing-lab** [comment]
关于`Polars中文教程`，是对[pola-rs/polars-book-cn](https://github.com/pola-rs/polars-book-cn)在数据处理与分析层面的推广，是开创大数据分析体系的前导工具教程。

这个由[pola-rs]()官方提供的中文文档仓库，是由[linjing-lab](https://github.com/linjing-lab)与[Subranium](https://github.com/SuperSupeng)提出[pola-rs/polars/issues/3211](https://github.com/pola-rs/polars/issues/3211)争取得来的。

在此要特别鸣谢：[linjing-lab](https://github.com/linjing-lab)、[苏鹏](https://github.com/SuperSupeng)、[沈豪](https://github.com/shenhao-stu)等成员的贡献与合作，才使得polars的中文文档能够顺利推出。


招募需求：
1. 掌握Python与Numpy的人，帮助完成教程的预备知识部分；
2. 对Pandas有较为深入的研究，理解API构建原理的人，帮助对比研读[Polars中文文档](https://pola-rs.github.io/polars-book-cn/user-guide/index.html)；
3. 有数据分析比赛过程中做特征工程的经验，能够将特征工程、数据挖掘等流程融合，来推出polars的应用与实战案例；
4. 掌握Rust编程、Apache Arrow的人，能够分析Polars的底层API设计机制的；
5. 对统计学、数据分析理论或实践有较为深入研究的人，同样欢迎大家能够参与到其中。

**Comment by linjing-lab** [comment]
### **你是否已经阅读并同意《Datawhale社区贡献协议》？**

- [x] 我已阅读并同意 [《Datawhale社区贡献协议》](https://github.com/datawhalechina/DOPMC/blob/main/CONTRIBUTING.md)

### 项目简介

本项目希望通过研读新型数据处理工具[Polars](https://github.com/pola-rs/polars)的中文文档，实现面向数据分析领域的一个中文教程，进而拓展数据科学学习生态。

项目参考文档：[Polars中文文档](https://pola-rs.github.io/polars-book-cn/user-guide/index.html)

### 立项理由

目前社区的数据分析课程是由pandas构建的，希望通过该项目帮助学习者学习一种新型的数据处理工具，并帮助学习者打开大数据处理的大门，缓解数据处理的难处。

### 项目受众

在线学校或数据分析行业从业者

### 项目亮点

该项目主要有以下几点内容较为创新：

- 采用新型数据处理工具Polars；
- 结合pandas特征工程对比学习；
- 搭建数据分析比赛案例分析；
- 从API设计分析的异同的角度进行分析学习。

### 项目规划

预计从7月25日开始，用两周时间构建本书的结构，项目共分为以下几个部分：

- Python基础
- Numpy基础
- 初识Polars
- Polars基础
- Polars进阶
- Polars高级
- 附属生态

### 项目负责人

微信：lj1439313331

### help wanted

[招募需求](https://github.com/datawhalechina/DOPMC/issues/29#issuecomment-1193076281)

- [x] 我已知悉上述备注

**Comment by Sm1les** [comment]
已重开新的：https://github.com/datawhalechina/DOPMC/issues/68
