### ISSUE TITLE
Polars中文教程

### ISSUE THREAD

**Issue by linjing-lab** [datawhalechina/DOPMC#68]
### 你是否已经阅读并同意《Datawhale社区贡献协议》？

- [x] 我已阅读并同意 [《Datawhale社区贡献协议》](https://github.com/datawhalechina/DOPMC/blob/main/CONTRIBUTING.md)

### 项目简介

本项目希望通过研读新型数据处理工具[Polars](https://github.com/pola-rs/polars)的中文文档，实现面向数据分析领域的一个中文教程，进而拓展数据科学学习生态。

项目参考文档：[Polars中文文档](https://pola-rs.github.io/polars-book-cn/user-guide/index.html)

### 立项理由

目前社区的数据分析课程是由pandas构建的，希望通过该项目帮助学习者学习一种新型的数据处理工具，并帮助学习者打开大数据处理的大门，缓解数据处理的难处。

### 项目受众

在校学生或数据分析行业从业者

### 项目亮点

该项目主要有以下几点内容较为创新：

- 采用新型数据处理工具Polars；
- 结合pandas特征工程对比学习；
- 搭建数据分析比赛案例分析；
- 从API设计分析的异同的角度进行分析学习。

### 项目规划

预计从7月25日开始，用两周时间构建本书的结构，项目共分为以下几个部分：

- Python基础
- Numpy基础
- 初识Polars
- Polars基础
- Polars进阶
- Polars高级
- 附属生态

![polars-tutorial](https://user-images.githubusercontent.com/82669431/180640762-b3c15992-f481-4de7-9b7a-cf42ee841aaf.png)

### 项目负责人

微信：lj1439313331
@linjing-lab

### help wanted

关于`Polars中文教程`，是对[pola-rs/polars-book-cn](https://github.com/pola-rs/polars-book-cn)在数据处理与分析层面的推广，是开创新数据分析体系的前导工具教程。

这个由[pola-rs](https://github.com/pola-rs)官方提供的中文文档仓库，是由[linjing-lab](https://github.com/linjing-lab)与[Subranium](https://github.com/SuperSupeng)提出[pola-rs/polars/issues/3211](https://github.com/pola-rs/polars/issues/3211)争取得来的。

在此要特别鸣谢：[linjing-lab](https://github.com/linjing-lab)、[苏鹏](https://github.com/SuperSupeng)、[沈豪](https://github.com/shenhao-stu)等成员的贡献与合作，才使得polars的中文文档能够顺利推出。

招募需求：
1. 掌握Python与Numpy的人，帮助完成教程的预备知识部分；
2. 对Pandas有较为深入的研究，理解API构建原理的人，帮助对比研读[Polars中文文档](https://pola-rs.github.io/polars-book-cn/user-guide/index.html)；
3. 有数据分析比赛过程中做特征工程的经验，能够将特征工程、数据挖掘等流程融合，来推出polars的应用与实战案例；
4. 掌握Rust编程、Apache Arrow的人，能够分析Polars的底层API设计机制的；
5. 对统计学、数据分析理论或实践有较为深入研究的人，同样欢迎大家能够参与到其中。

### 备注：发起立项申请后DOPMC将会在 72h 之内给出答复，如超时未答复请添加DOPMC负责人微信（微信号：at-Sm1les）问询~

- [x] 我已知悉上述备注

**Comment by mba1398** [comment]
同意

**Comment by GYHHAHA** [comment]
同意

**Comment by skywateryang** [comment]
同意

**Comment by NoFish-528** [comment]
同意 建议更加细化下

**Comment by ruyiluo** [comment]
现有的polars文档（https://pola-rs.github.io/polars-book-cn/user-guide/index.html）感觉已经非常详细了，再做一遍是不是比较难做出差异化，如果可以的话，建议先把每个小节的内容的规划再细化一下，看能否体现出一定的差异化，或者想办法做一些调研，看现有的这个文档存在哪些不足的地方？

比较担心，花了人力做了，然后效果远差预期！

关于立项理由的话，我觉得不应该是社区缺少什么就去做什么，而是得看大家需要什么，再考虑是否要去做什么，这块可以提前调研一下？【个人看法】

**Comment by linjing-lab** [comment]
> 

这个是在一次比赛中用Pandas做特征工程时产生的想法，因为在做`.read_excel`与`.concat`方法时Pandas的速度比较的慢，所以采用了一种代替产品：Polars，发现他对大数据的处理效果要比pandas好很多。

再者是polars文档，官方的可能还是比较难以理解，对于大部分的**在校学生**或者说**数据分析行业从业者**来说（项目受众），不是特别的友好。如果从每一小节内容进行细化的话，首先可能很难找到懂一些底层设计的人去做它（所以招募的人中写到了需要找一部分会底层API设计的来），我认为最好的方式是通过枚举**案例**的方式进行细化，在我的项目规划里面有写到。

现在的小数据实际上成为了对于Pandas来说的“大数据”，较大规模的数据对于Pandas来说反而是一种负担，人们更想看到一个较大规模的数据能够快速导入至Python工作环境（即减小等待忧虑），随后可以便捷轻松的开展实验等。（也可以说符合大部分还未掌握大数据处理工具的想法）

**Comment by ruyiluo** [comment]
同意！

**Comment by linjing-lab** [comment]
已经更新项目规划：https://github.com/datawhalechina/DOPMC/issues/68#issue-1315658202

**Comment by qiwang067** [comment]
同意 :)

**Comment by GYHHAHA** [comment]
@linjing-lab 你这里说的大数据它有多大？超过单机内存吗？另外请把项目的第一部分和第二部分关于numpy和python基础的内容删掉，现在这部分材料已经够多了，况且如果这两个基础部分有问题的同学不适合学习这个教程。此外，这个教程应该把“大”数据分析的实践案例放到最重要的位置，必须保证几乎每个例子都无法较好地利用pandas来处理，并且这个任务足够复杂，而不是toy/demo example。换句话说，我觉得你应该把6.4节内容单独写两个章节（至少一个章节）来讨论包含但不限于以下①性能优化的benchmark构建②polas优化的常见思路③怎么估计polas代码的效率（相对于其他框架）④为什么快，原理分析⑤利用扩展进行性能加速（把第七章重新规划然后放进来）。从直觉上讲，看这个教程的人都会pandas，剩下应该有一章基于两边函数/数据结构方法的对比，让pandas用户快速适应polas。供参考。

**Comment by finlay-liu** [comment]
如果只是翻译文档，不建议做。

**Comment by Sm1les** [comment]
@andongBlue @zhanhao93 @finlay-liu 在DOPMC群中表示同意

**Comment by Sm1les** [comment]
同意

**Comment by linjing-lab** [comment]
招募需求：
1. 掌握Python与Numpy的人，帮助完成教程的预备知识部分；
2. 对Pandas有较为深入的研究，理解API构建原理的人，帮助对比研读[Polars中文文档](https://pola-rs.github.io/polars-book-cn/user-guide/index.html)；
3. 有数据分析比赛过程中做特征工程的经验，能够将特征工程、数据挖掘等流程融合，来推出polars的应用与实战案例；
4. 掌握Rust编程、Apache Arrow的人，能够分析Polars的底层API设计机制的；
5. 对统计学、数据分析理论或实践有较为深入研究的人，同样欢迎大家能够参与到其中
