### ISSUE TITLE
新手入门必备知识技能汇总

### ISSUE THREAD

**Issue by SherryTECNU** [datawhalechina/DOPMC#71]
### Discussed in https://github.com/datawhalechina/DOPMC/discussions/70

<div type='discussions-op-text'>

<sup>Originally posted by **SherryTECNU** July 26, 2022</sup>
我是从去年开始入门数据分析，多次参加Datawhale的学习，担任过队长，也当过助教，期间认识了许多和我一样从Datawhale入门的小伙伴，许多和我一样在早期都会有一种困惑，课程很多，应该从什么地方开始，要学习多少课程才能入门，学习到何种程度才能算入门，可以上手做项目。希望邀请各个领域有较深研究的小伙伴来提供知识图谱，让入门学习者了解所需入门领域最需要掌握的基础知识内容，以及各知识间的内在关系或逻辑。也相当于以自己为例，做一个学习流程的例子推荐，给入门学习者提供一个学习指导和方向。</div>

**Comment by SuperSupeng** [comment]
可以再将需求以及解决方案具体明确一下，比如现阶段想要做什么，做成什么样，是否可以拆分分阶段来做。

**Comment by xiaoxiaoyao** [comment]
换个思路，以终为始，先想一下你希望学到什么程度，然后逆向思考需要哪些知识点
