### ISSUE TITLE
课程流程模板优化

### ISSUE THREAD

**Issue by SherryTECNU** [datawhalechina/DOPMC#73]
### Discussed in https://github.com/datawhalechina/DOPMC/discussions/72

<div type='discussions-op-text'>

<sup>Originally posted by **SherryTECNU** July 27, 2022</sup>
有的课程设置不太能激励学习者持续打卡，也不方便学习者提炼需要掌握的知识点，希望结合各个优秀课程提供一个课程设计的参考模板，可以更好激励学习者学习，目前有的建议是：
（1） 课程前设置课程重点：明确需要掌握的基础目标，以及更高一层要求的提升目标。改内容可以是总结式，也可以是抛出问题，让学习者带着问题学习
（2） 课程结束模块基于学习知识，提出独立的课后练习，让同学习者了解知识掌握情况，我觉得也可以决绝一下笔记和学习资料太像问题。
以上只是一些小建议，希望有更多的学习者提出建议认为什么样的模式更适合学习。</div>

**Comment by SuperSupeng** [comment]
这两点建议拿现在正在进行中的教程进行尝试，并将最终内容总结形成课程建设的标准化流程
