### ISSUE TITLE
《统计学习方法（第2版）》读书笔记：statistical-learning-method-study-notebook

### ISSUE THREAD

**Issue by Harold-Ran** [datawhalechina/DOPMC#86]
### 你是否已经阅读并同意《Datawhale开源项目行为准则》？

- [X] 我已阅读并同意[《Datawhale开源项目行为准则》](https://github.com/datawhalechina/DOPMC/blob/main/CODE_OF_CONDUCT.md)

### 项目简介

李航老师的《统计学习方法》作为算法初学者的入门必读书籍，以其逻辑清晰、条理分明的讲述广受读者赞誉，然而这本书公式繁多、内容充实，对于基础一般的初学者来说要全面理解书中的内容还是比较困难。本项目基于《统计学习方法（第2版）》，对书中的章节以笔记的形式进行解读，旨在作为该书的辅助学习手册，用更加直白易懂的语言帮助初学者理解书中的内容。

### 立项理由

1、《统计学习方法》是算法的经典入门书籍，但是对于基础一般的初学者来说要全面理解书中的内容还是比较困难，本项目旨在作为该书的辅助学习手册，用更加直白易懂的语言帮助初学者理解书中的内容。
2、我们社区已经有了《统计学习方法（第2版）》课后习题解答项目，本项目作为该书的读书笔记，能够结合习题解答项目，提供给初学者从内容学习到课后习题的一个完整的学习路径。

### 项目受众

本项目主要面向想要从《统计学习方法》一书开始学习算法的初学者

### 项目亮点

《统计学习方法》这本书的解读项目在互联网上非常多，但是内容质量参差不齐，对于初学者来说要从中筛选出优质的内容并非易事。本项目旨在作为读书笔记帮助初学者更快速地理解书中内容，结合课后习题解答项目，构建扎实的算法基础。

### 项目规划

**各章节负责人：**
- 1-3章：邱雯
- 7-8章：魏浩原
- 9-10章：左凯文
- 11-12章：陈锴
- 13-15章：王威
- 16-17章：揭熔阳
- 20-22章：惠雨乔
- 4-6章及18-19章：曾海如

**项目排期：**
10.10-10.30 完成初稿
10.31-11.13 审核修改

### 项目负责人

GitHub：https://github.com/Harold-Ran
Wechat：zhr17863135721

### 备注：发起立项申请后DOPMC将会在 72h 之内给出答复，如超时未答复请添加DOPMC负责人微信（微信号：at-Sm1les）问询~

- [X] 我已知悉上述备注

**Comment by NoFish-528** [comment]
1. 有无样章展示 @Harold-Ran

**Comment by Harold-Ran** [comment]
项目这周才开始做，暂时没有样章展示

**Comment by Harold-Ran** [comment]
> 1. 有无样章展示 @Harold-Ran

项目这周才开始做，暂时没有样章展示

**Comment by finlay-liu** [comment]
同意

**Comment by andongBlue** [comment]
这个和锐锋学长的内容有什么区别吗？差异化是什么呢？

**Comment by skywateryang** [comment]
项目亮点中提到“这本书的解读项目在互联网上非常多，但是内容质量参差不齐”
是否可以举一些具体的例子，对比下表明本项目的优势在哪

**Comment by ruyiluo** [comment]
这个是不是可以考虑和锋哥的习题一起搞一下

读书笔记+习题解？

**Comment by mba1398** [comment]
建议合并（读书笔记和习题解答）。

**Comment by GYHHAHA** [comment]
同样建议合并

**Comment by andongBlue** [comment]
建议强强联合
